# -= Join on join =-
# If true, players that join the server will join the parkour.
join-on-join: false

# -= Permissions =-
# If true, the plugin will use permissions
permissions: false

# -= Time format =-
# H = hours, m = minutes, s = seconds, S = milliseconds
time-format: "mm:ss:SSS"

# -= Mode settings =-
mode-settings:
  close:
    # -= Radius =-
    # The radius of the allowed area around the center
    radius: 4.0

  min-speed:
    # -= The min speed =-
    # The min speed in m/s
    min-speed: 35.0

    # -= Actionbar length =-
    # The length of the actionbar
    actionbar-length: 30

  time-trial:

    # -= Seed =-
    seed: 0

    # -= Score =-
    # The score the player needs to reach to complete the parkour
    score: 2500.0

    # -= Actionbar length =-
    # The length of the actionbar
    actionbar-length: 30

# -= Styles =-
styles:
  random:
    cherry: [ "cherry_wood", "stripped_cherry_wood", "cherry_planks", "cherry_slab", "cherry_stairs", "cherry_fence" ]
    spruce: [ "spruce_wood", "stripped_spruce_wood", "spruce_planks", "spruce_slab", "spruce_stairs", "spruce_fence" ]
    crimson: [ "crimson_hyphae", "stripped_crimson_hyphae", "crimson_planks", "crimson_slab", "crimson_stairs", "crimson_fence" ]
    bamboo: [ "bamboo_block", "stripped_bamboo_block", "bamboo_planks", "bamboo_mosaic", "bamboo_stairs", "bamboo_mosaic_stairs",
              "bamboo_slab", "bamboo_mosaic_slab", "bamboo_fence" ]
    glass: ["white_stained_glass"]
  incremental:
    herring: ["barrier", "barrier", "barrier", "barrier", "barrier", "barrier", "barrier", "barrier", "barrier",
              "barrier", "barrier", "red_concrete"]