# Infinite Elytra Parkour
# by Efnilite
# (c) 2024

# Need help?
# Join my Discord (https://efnilite.dev/discord) or email me (https://efnilite.dev/#contact).

# -= Debug =-
debug: false

# -= Join on join =-
# If true, players that join the server will join the parkour.
join-on-join: false

# -= Permissions =-
# If true, the plugin will use permissions
permissions: false

# -= Time format =-
# H = hours, m = minutes, s = seconds, S = milliseconds
time-format: "mm:ss:SSS"

# -= Default measurement system =-
# If true, metric is used. If false, imperial is used.
metric: true

# -= MySQL =-
mysql:

  # -= MySQL enabled? =-
  enabled: false

  url: "localhost:3306/iep"
  username: "username"
  password: "password"

# -= Mode settings =-
mode-settings:
  close:
    enabled: true

  min-speed:
    enabled: true

    # -= The min speed =-
    # The min speed in m/s
    min-speed: 35.0

    # -= Actionbar length =-
    # The length of the actionbar
    actionbar-length: 30

  obstacle:
    enabled: true

  speed-demon:
    enabled: true

  time-trial:
    enabled: true

    # -= Seed =-
    seed: 0

    # -= Score =-
    # The score the player needs to reach to complete the parkour
    score: 2500.0

    # -= Actionbar length =-
    # The length of the actionbar
    actionbar-length: 30

# -= Styles =-
# Styles should have some see-through materials, like slabs or fences.
# This avoids dark areas.
styles:
  random:
    cherry: [ cherry_wood, stripped_cherry_wood, cherry_planks, cherry_slab, cherry_stairs, cherry_fence ]
    spruce: [ spruce_wood, stripped_spruce_wood, spruce_planks, spruce_slab, spruce_stairs, spruce_fence ]
    crimson: [ crimson_hyphae, stripped_crimson_hyphae, crimson_planks, crimson_slab, crimson_stairs, crimson_fence ]
    bamboo: [ bamboo_block, stripped_bamboo_block, bamboo_planks, bamboo_mosaic, bamboo_stairs, bamboo_mosaic_stairs, bamboo_slab, bamboo_mosaic_slab, bamboo_fence ]
    nether: [ netherrack, nether_bricks, red_nether_bricks, chiseled_nether_bricks, nether_gold_ore, netherite_block, basalt, nether_brick_fence, red_nether_brick_wall, nether_brick_stairs, nether_brick_slab, red_nether_brick_stairs, red_nether_brick_slab ]
    glass: [ white_stained_glass ]
  incremental:
    spiral: [ barrier, barrier, barrier, barrier, red_concrete ]